### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by jaskaran87** [jsocol/sphinxapi#3]
I did not get how to use this, Can you please give any documentation, I have implement sphinx search in php now i am going to implement this in python but geting error 

python3

import sphinxapi 

client = sphinxapi.SphinxClient()

client.SetServer('127.0.0.1',9312)

client.Query("english","language_index")

geting error 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/sphinxapi/__init__.py", line 579, in Query
    assert (len(self._reqs) == 0)
AssertionError

Please can anyone help me to sort this

**Comment by jsocol** [comment]
This repo is something like 6 years out of date—it's definitely never been tested with Python 3. Originally it was just a pip-installable mirror of another source, but unfortunately I can't find it on sphinxsearch.com anymore.

It's probably best to try to find a more up-to-date Python client, or maybe fork this and update it. Unfortunately I'm not able to spend time on this one anymore.
